tasks:
  - init: |
      curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
      chmod +x ./kind
      curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
      curl -fsSL https://github.com/tilt-dev/ctlptl/releases/download/v0.6.1/ctlptl.0.6.1.linux.x86_64.tar.gz | sudo tar -xzv -C /usr/local/bin ctlptl
    command: |
      ctlptl apply -f ./kind-config.yaml
      tilt up