apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: blog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-api
  template:
    metadata:
      labels:
        app: blog-api
    spec:
      containers:
        - name: blog-api
          image: blog-api
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              port: 5000
              path: '/ready'
          env:
            - name: PGHOST
              value: "db.default"
            - name: PGUSER
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: blog-api
  ports:
    - name: express
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: apollo
      protocol: TCP
      port: 4000
      targetPort: 4000