apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: blog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-db
  template:
    metadata:
      labels:
        app: blog-db
    spec:
      containers:
        - name: blog-db
          image: blog-db
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "strongpassword"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: blog-db
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432