apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: blog-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-web
  template:
    metadata:
      labels:
        app: blog-web
    spec:
      containers:
        - name: blog-web
          image: blog-web
          ports:
            - containerPort: 3000